name: "Project Report Generator"
description: "Generates a comprehensive report about the project, including directory structure, tech stack, and usage."
author: "Mayank Singh"
branding:
  icon: "file-text"
  color: "blue"
inputs:
  report_format:
    description: "The format of the report (html or md)."
    required: true
    default: "md"
  exclude_files:
    description: "Comma-separated list of files or folders to exclude from analysis."
    required: false
    default: ""
  upload_artifact:
    description: "Upload the generated report as an artifact."
    required: false
    default: "false"
  commit_report:
    description: "Commit the generated report to the repository."
    required: false
    default: "false"
outputs:
  report_path:
    description: "The path to the generated report."
runs:
  using: "node16"
  main: "index.js"
