name: Run Project Analysis Action

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies (make sure your package.json exists)
      - name: Install dependencies
        run: npm install

      # Step 4: Install git (though this might already be available by default)
      - name: Install git
        run: sudo apt-get install -y git

      # Step 5: Run your project analysis action
      - name: Run project analysis action
        uses: ./  # Ensure this points to your custom action

      # Step 6: Commit and push the generated report
      - name: Commit and push report
        env:
          # Use the GitHub token to authenticate
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Mayank Singh"
          git config --global user.email "msrajawat298@gmail.com"
          
          # Add the report file (ensure it's generated by the analysis action)
          git add ./project-report.md
          
          # Commit the changes
          git commit -m "Add project report"
          
          # Push the changes back to the repository
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
