name: Run Project Analysis Action

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run project analysis action
        uses: ./
        with:
          exclude_files: 'node_modules,build,.git'
          commit_report: 'true'